export const UPDATE_FOO = "UPDATE_FOO";
export const UPDATE_HOST = "UPDATE_HOST";
export const SET_HOST_STATE = "SET_HOST_STATE";
export const UPDATE_NAME = "UPDATE_NAME";
export const UPDATE_USER_TITLE = "UPDATE_USER_TITLE"
export const SET_HOST_DEFAULT_TITLE = "SET_HOST_DEFAULT_TITLE";

// export default {
// UPDATE_FOO = "UPDATE_FOO",
// SET_HOST_STATE = "SET_HOST_STATE",
// UPDATE_NAME = "UPDATE_NAME",
// SET_HOST_DEFAULT_TITLE = "SET_HOST_DEFAULT_TITLE",
// }