export const SET_IS_APPENDED = "SET_IS_APPENDED";
export const SET_USER_TITLE = "SET_USER_TITLE";
export const SET_HOST_STATE = "SET_HOST_STATE";
export const SET_DEFAULT_TITLE = "SET_DEFAULT_TITLE";
export const SET_ORIGINAL_TAB_TITLE = "SET_ORIGINAL_TAB_TITLE";
